CREATE TABLE IF NOT EXISTS users(id SERIAL PRIMARY KEY);
CREATE TABLE IF NOT EXISTS gists(id SERIAL PRIMARY KEY);
CREATE TABLE IF NOT EXISTS comments(id SERIAL PRIMARY KEY);
INSERT INTO users DEFAULT VALUES;
INSERT INTO gists DEFAULT VALUES;
INSERT INTO comments DEFAULT VALUES;
