apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: app-secrets
  namespace: gistpin-prod
spec:
  encryptedData:
    DATABASE_URL: AgREPLACE_WITH_SEALED_VALUE
    JWT_SECRET: AgREPLACE_WITH_SEALED_VALUE
    REDIS_URL: AgREPLACE_WITH_SEALED_VALUE
  template:
    metadata:
      name: app-secrets
      namespace: gistpin-prod
    type: Opaque
