apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: gistpin-vault
  namespace: gistpin-prod
spec:
  provider:
    kubernetes:
      remoteNamespace: security-secrets
      server:
        caProvider:
          type: ConfigMap
          name: kube-root-ca.crt
          key: ca.crt
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: app-secrets
  namespace: gistpin-prod
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: gistpin-vault
    kind: SecretStore
  target:
    name: app-secrets
    creationPolicy: Owner
  data:
    - secretKey: DATABASE_URL
      remoteRef:
        key: gistpin/database-url
    - secretKey: JWT_SECRET
      remoteRef:
        key: gistpin/jwt-secret
    - secretKey: REDIS_URL
      remoteRef:
        key: gistpin/redis-url
