apiVersion: v1
kind: ServiceAccount
metadata:
  name: backend-sa
  namespace: gistpin-dev
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: frontend-sa
  namespace: gistpin-dev
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: backend-sa
  namespace: gistpin-staging
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: frontend-sa
  namespace: gistpin-staging
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: backend-sa
  namespace: gistpin-prod
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: frontend-sa
  namespace: gistpin-prod
