apiVersion: v1
kind: ServiceAccount
metadata:
  name: backend
  namespace: gistpin
  annotations:
    eks.amazonaws.com/role-arn: "arn:aws:iam::ACCOUNT_ID:role/gistpin-backend-irsa"
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: frontend
  namespace: gistpin
  annotations:
    eks.amazonaws.com/role-arn: "arn:aws:iam::ACCOUNT_ID:role/gistpin-frontend-irsa"
