version: ">=0.17.0"
formatter: markdown table

settings:
  indent: 2
  required: true
  sensitive: true
  default: true
  type: true
  escape: true

sections:
  show:
    - inputs
    - outputs
    - resources

output:
  file: README.md
  mode: inject
  template: |-
    <!-- BEGIN_TF_DOCS -->
    {{ .Content }}
    <!-- END_TF_DOCS -->
