#!/usr/bin/env python3
"""Generate Terraform reconciliation fixes from a plan JSON.

Reads the JSON produced by `terraform show -json <plan>`, categorizes each
resource change (drift), writes a human-readable reconciliation report, and
emits generated fix configuration:

  * in-place updates  -> reported (config already reconciles them on apply)
  * replacements      -> reported with the attributes forcing replacement
  * deletes           -> reported (state has a resource config no longer wants)
  * import-needed      -> `import {}` blocks for resources that exist in reality
                         but are missing from state

The generated fixes are advisory; nothing is applied here.
"""
import argparse
import json
import sys
from collections import defaultdict


def categorize(change):
    """Map a resource_change's actions to a drift category."""
    actions = change.get("change", {}).get("actions", [])
    if actions == ["update"]:
        return "update"
    if actions in (["delete", "create"], ["create", "delete"]):
        return "replace"
    if actions == ["delete"]:
        return "delete"
    if actions == ["create"]:
        # A create in a reconciliation plan usually means state is missing a
        # resource that the config declares (candidate for import).
        return "import-needed"
    return "other"


def replacement_attrs(change):
    """Attributes that force replacement, if any."""
    return change.get("change", {}).get("replace_paths", []) or []


def build_import_block(address, change):
    """Best-effort `import {}` block for a resource missing from state.

    The real resource id must be supplied by the operator; we scaffold the block
    and leave a clearly-marked placeholder rather than guessing an id.
    """
    return (
        f"# Resource '{address}' is declared in config but absent from state.\n"
        f"# If it already exists in the cloud, import it (replace REAL_ID):\n"
        f"import {{\n"
        f"  to = {address}\n"
        f'  id = "REAL_ID"  # TODO: set the real resource id\n'
        f"}}\n\n"
    )


def main(argv=None):
    parser = argparse.ArgumentParser(description="Generate Terraform reconciliation fixes")
    parser.add_argument("--plan-json", required=True, help="terraform show -json output")
    parser.add_argument("--report", required=True, help="path to write the markdown report")
    parser.add_argument("--fixes", required=True, help="path to write generated fix config")
    args = parser.parse_args(argv)

    with open(args.plan_json) as fh:
        plan = json.load(fh)

    changes = plan.get("resource_changes", [])
    buckets = defaultdict(list)
    for change in changes:
        category = categorize(change)
        if category == "other":
            continue
        buckets[category].append(change)

    # --- Report -------------------------------------------------------------
    lines = ["# Terraform Reconciliation Report", ""]
    total = sum(len(v) for v in buckets.values())
    lines.append(f"Detected drift on **{total}** resource(s).")
    lines.append("")

    labels = {
        "update": "In-place updates (config reconciles on apply)",
        "replace": "Replacements (destroy + recreate)",
        "delete": "Deletions (state has a resource config no longer declares)",
        "import-needed": "Import needed (config declares a resource missing from state)",
    }
    for category in ("update", "replace", "delete", "import-needed"):
        items = buckets.get(category, [])
        if not items:
            continue
        lines.append(f"## {labels[category]} — {len(items)}")
        lines.append("")
        for change in items:
            address = change.get("address", "<unknown>")
            if category == "replace":
                forcing = ", ".join(".".join(map(str, p)) for p in replacement_attrs(change))
                lines.append(f"- `{address}` — forced by: {forcing or 'unknown'}")
            else:
                lines.append(f"- `{address}`")
        lines.append("")

    with open(args.report, "w") as fh:
        fh.write("\n".join(lines))

    # --- Generated fixes ----------------------------------------------------
    fix_lines = [
        "# Generated by generate-fix-configs.py — review before use.",
        "# Nothing here is applied automatically.",
        "",
    ]
    for change in buckets.get("import-needed", []):
        fix_lines.append(build_import_block(change.get("address", "<unknown>"), change))

    if len(fix_lines) == 3:
        fix_lines.append("# No import blocks needed; drift is reconciled by the existing config on apply.\n")

    with open(args.fixes, "w") as fh:
        fh.write("\n".join(fix_lines))

    print(f"Categorized {total} drifted resource(s): "
          + ", ".join(f"{k}={len(v)}" for k, v in sorted(buckets.items())))
    return 0


if __name__ == "__main__":
    sys.exit(main())
