apiVersion: v1
kind: ConfigMap
metadata:
  name: frontend-config
  namespace: gistpin-prod
data:
  NEXT_PUBLIC_APP_NAME: GistPin
  NEXT_PUBLIC_API_URL: https://api.gistpin.app
  NEXT_PUBLIC_CDN_URL: https://cdn.gistpin.app
